// <auto-generated />
using System;
using FuelGuard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuelGuard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FuelGuardDbContext))]
    [Migration("20260507203534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuelGuard.Domain.Entities.AnomalyDetection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TankId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TankId");

                    b.ToTable("AnomalyDetections");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.DailyFuelSnapshot", b =>
                {
                    b.Property<Guid>("TankId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("ClosingStock")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpeningStock")
                        .HasColumnType("numeric");

                    b.HasKey("TankId", "Date");

                    b.ToTable("DailyFuelSnapshots");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.FuelTank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacityLiters")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("FuelTanks");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.FuelTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuantityLiters")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TankId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TankId");

                    b.ToTable("FuelTransactions");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.RiskScore", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("CompanyId");

                    b.ToTable("RiskScores");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.AnomalyDetection", b =>
                {
                    b.HasOne("FuelGuard.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelGuard.Domain.Entities.FuelTank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.DailyFuelSnapshot", b =>
                {
                    b.HasOne("FuelGuard.Domain.Entities.FuelTank", "Tank")
                        .WithMany("DailySnapshots")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.FuelTank", b =>
                {
                    b.HasOne("FuelGuard.Domain.Entities.Company", "Company")
                        .WithMany("Tanks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.FuelTransaction", b =>
                {
                    b.HasOne("FuelGuard.Domain.Entities.Company", "Company")
                        .WithMany("Transactions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelGuard.Domain.Entities.FuelTank", "Tank")
                        .WithMany("Transactions")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.RiskScore", b =>
                {
                    b.HasOne("FuelGuard.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.Company", b =>
                {
                    b.Navigation("Tanks");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FuelGuard.Domain.Entities.FuelTank", b =>
                {
                    b.Navigation("DailySnapshots");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
