/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        error: '#ffb4ab',
        tertiary: '#4edea3',
        'secondary-fixed-dim': '#c6c6cc',
        'on-secondary-fixed-variant': '#45474b',
        'on-tertiary-container': '#000703',
        background: '#101415',
        'on-tertiary-fixed': '#002113',
        'tertiary-container': '#00885d',
        'on-secondary-container': '#b7b8be',
        'on-primary-fixed-variant': '#2f2ebe',
        outline: '#908fa0',
        'on-tertiary-fixed-variant': '#005236',
        'primary-fixed': '#e1e0ff',
        surface: '#101415',
        'surface-container-highest': '#323537',
        'surface-variant': '#323537',
        'surface-container-lowest': '#0b0f10',
        'surface-container-high': '#272a2c',
        'outline-variant': '#464554',
        'tertiary-fixed-dim': '#4edea3',
        'inverse-primary': '#494bd6',
        'on-primary-container': '#0d0096',
        'secondary-fixed': '#e2e2e8',
        'on-surface-variant': '#c7c4d7',
        'on-tertiary': '#003824',
        'surface-bright': '#363a3b',
        'on-secondary-fixed': '#1a1c20',
        'inverse-surface': '#e0e3e5',
        'on-error': '#690005',
        'primary-fixed-dim': '#c0c1ff',
        'surface-tint': '#c0c1ff',
        'primary-container': '#8083ff',
        'inverse-on-surface': '#2d3133',
        primary: '#c0c1ff',
        'on-surface': '#e0e3e5',
        'surface-dim': '#101415',
        'surface-container': '#1d2022',
        'on-primary-fixed': '#07006c',
        'on-error-container': '#ffdad6',
        'tertiary-fixed': '#6ffbbe',
        'on-secondary': '#2f3035',
        secondary: '#c6c6cc',
        'secondary-container': '#47494e',
        'surface-container-low': '#191c1e',
        'on-primary': '#1000a9',
        'error-container': '#93000a',
        'on-background': '#e0e3e5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        gutter: '16px',
        unit: '4px',
        'stack-xs': '4px',
        'stack-sm': '8px',
        'container-max': '1440px',
        'stack-md': '16px',
        'stack-lg': '24px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'data-tabular': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'data-tabular': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
